 name: predicates test

on:
  workflow_dispatch:
  pull_request:
  push:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Print environment
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install dependencies on unx
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          g++ --version

      - name: Build predicates
        run: g++ -std=c++17 -pedantic -Wall -O3 -flto -DNDEBUG \
             example.cpp -oexample

      - name: Check predicates
        run: ./example
